# Generated by Django 5.1.4 on 2025-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deuda_manual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
